In [3]:
import numpy as np

A = np.array([0,1,2,3,4,5,6,7,8,9])
A = A.reshape(1,-1)
A.shape

(1, 10)

In [4]:
A = np.array([[[ 0, 1, 2, 3],[ 4, 5, 6, 7],[ 8, 9, 10, 11]],[[12, 13, 14, 15],[16, 17, 18, 19],[20, 21, 22, 23]]])

In [9]:
A.shape

(2, 3, 4)

In [11]:
A.reshape(2,3,4)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [19]:
B = A.T
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
A.reshape(2,3,4)

array([[[ 0, 12,  4, 16],
        [ 8, 20,  1, 13],
        [ 5, 17,  9, 21]],

       [[ 2, 14,  6, 18],
        [10, 22,  3, 15],
        [ 7, 19, 11, 23]]])

In [21]:
y = np.array([[0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0], [0.1, 0.05, 0.2, 0.0, 0.05, 0.1, 0.0, 0.5, 0.0, 0.0]])
t = np.array([2, 7])

In [30]:
np.array([y[0, t[0]], y[1, t[1]]])

array([0.6, 0.5])

In [31]:
y[np.arange(2), t]

array([0.6, 0.5])

## day 009 - quest 7, 8

Q4. 이상치를 구하는 방법인 z-score와 IQR method 차이점